### ISSUE TITLE
Assignment 1 factorial calculator

### ISSUE THREAD

**Issue by 62bit23** [vtcbca/basic-programming-62bit23#2]

**Comment by 62bit23** [comment]
Hey, do you know what a factorial is?

**Comment by 65bit23** [comment]
Yeah! A factorial is the product of all positive whole numbers up to a certain number.

**Comment by 62bit23** [comment]
So if I want to find factorial of 5 ?

**Comment by 65bit23** [comment]
Just multiply 5 × 4 × 3 × 2 × 1

**Comment by 62bit23** [comment]
It means **5** factorial is **120**

**Comment by 65bit23** [comment]
Exactly its denoted by **!** 5!=120.

**Comment by 65bit23** [comment]
Cool!

**Comment by 62bit23** [comment]
cool!
