### ISSUE TITLE
Assignment 3 Fibonacci Sequence

### ISSUE THREAD

**Issue by 62bit23** [vtcbca/basic-programming-62bit23#3]
what is Fibonacci Sequence ?

**Comment by 44bit23** [comment]
The Fibonacci sequence is a list of numbers where each number is the sum of the two before it.

**Comment by 62bit23** [comment]
i couldn't understand ! can you explain in detail?

**Comment by 44bit23** [comment]
The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting with 0 and 1.

**Comment by 62bit23** [comment]
can you explain it with example

**Comment by 44bit23** [comment]
0, 1, (0 + 1 = 1), (1 + 1 = 2), (1 + 2 = 3), (2 + 3 = 5), (3 + 5 = 8), (5 + 8 = 13), and so on.

So the sequence looks like this:
0, 1, 1, 2, 3, 5, 8, 13, ...

**Comment by 62bit23** [comment]
Okay, now I understand.
