### ISSUE TITLE
Assignment-2:  Prime Number Checker

### ISSUE THREAD

**Issue by 43bit23** [vtcbca/basic-programming-62bit23#4]
What is a prime number?

**Comment by 62bit23** [comment]
A prime number is a number greater than 1 that has only two factors: 1 and itself.

**Comment by 43bit23** [comment]
Can a negative number be a prime number?

**Comment by 62bit23** [comment]
No, prime numbers are always positive integers greater than 1.

**Comment by 43bit23** [comment]
How do you check if a number is prime?

**Comment by 62bit23** [comment]
Divide the number by all integers from 2 to the square root of the number. If none divide evenly, it is prime.

**Comment by 43bit23** [comment]
Can you use a list to store prime numbers?

**Comment by 62bit23** [comment]
Yes, you can store prime numbers in a list and iterate through it for efficient checking.

**Comment by 43bit23** [comment]
How do you modify the program to check a list of numbers for primes?

**Comment by 62bit23** [comment]
Use a loop to iterate through the list and apply the prime checking logic to each number.
